# Generated by Django 3.2.2 on 2021-05-14 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0002_rename_school_student_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='School',
            new_name='school',
        ),
    ]
