# Generated by Django 3.2.2 on 2021-05-14 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0003_rename_school_student_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='faculty',
            new_name='Faculty',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='certificate_type',
            new_name='Certificate_Type',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='Grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school',
            new_name='School',
        ),
    ]
