# Generated by Django 3.2.2 on 2021-05-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0004_auto_20210514_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Faculty',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Department',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Grade',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='School',
            new_name='school',
        ),
    ]
