# Generated by Django 3.2.2 on 2021-05-15 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0005_auto_20210514_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Certificate_Type',
            new_name='certificate_type',
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schooltracker.faculty'),
        ),
    ]
