# Generated by Django 3.2.2 on 2021-05-15 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0006_auto_20210515_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='certificate_type',
            new_name='Certificate_Type',
        ),
        migrations.AlterField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='schooltracker.faculty'),
            preserve_default=False,
        ),
    ]
