# Generated by Django 3.2.2 on 2021-05-15 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0009_alter_department_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Certificate_Type',
            new_name='certificate_type',
        ),
    ]
