# Generated by Django 3.2.2 on 2021-05-15 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0010_rename_certificate_type_student_certificate_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name': 'Faculty'},
        ),
    ]
