# Generated by Django 3.2.2 on 2021-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0011_alter_faculty_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={},
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Faculty'),
        ),
    ]
