# Generated by Django 3.2.2 on 2021-05-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooltracker', '0013_auto_20210515_1018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculty'},
        ),
    ]
